import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from '../components/Layout/Navbar';
import Footer from '../components/Layout/Footer';
import Container from '../components/Layout/Container';
import LanguageSwitcher from '../components/Shared/LanguageSwitcher';
import GoogleAnalytics from '@/components/googleAnalytics'
import './globals.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    
   // google Analytics
    const GA_TRACKING_ID = process.env.NEXT_PUBLIC_GA_TRACKING_ID;


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
                <GoogleAnalytics trackingId={GA_TRACKING_ID} />

        <Navbar />
        {/* <LanguageSwitcher /> */}
        <Container>
          {children}
        </Container>
        <Footer />
      </body>
    </html>
  );
}
